web/web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('website.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

web/website/urls.py
from django.urls import path,include
from .views import (
    HomeView,
    # Productcat,
    ProductDetailView,
    add_to_cart,
    remove_from_cart,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    Category,
)

app_name = 'web'
urlpatterns = [
    path('',HomeView.as_view() , name = "Home"),
    # path('', Category, name="Home"),
    path('checkout/', CheckoutView.as_view(), name="checkout"),
    path('page/pro_info/<slug>/', ProductDetailView.as_view(), name = "proinfo" ),
    path('add-to-cart/<slug>/', add_to_cart, name="add-to-cart"),
    path('remove-from-cart/<slug>/', remove_from_cart, name="remove-from-cart"),
    path('order-summary/', OrderSummaryView.as_view(), name="order-summary"),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name="remove-single-item-from-cart"),

    # path('page/productcat/<int:id>', Productcat, name="productcat"),
    # path('home/addcart',addcart, name="addcart"),
    # path('home/shoppingcart',shoppingcart, name="shoppingcart"),
    # path('home/order',getshoping , name="order_success"),
]

web/product/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    title = models.CharField(default='',max_length=100)
    slug = models.CharField(default='',max_length=100)
    description = models.TextField(default='')
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(default='',max_length=100)
    description = models.TextField(default='')
    active = models.BooleanField(default=True)
    price = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    img = models.ImageField(null=True)

    def __str__(self):
        return self.title

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete= models.CASCADE)
    title = models.CharField(default='',max_length=100)
    price = models.IntegerField(default=0)
    sale_price = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    inventory = models.IntegerField(default=0)

    def __str__(self):
        return self.title

web/website/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django.utils import timezone


# Create your models here.

class Category(models.Model):
    title = models.CharField(default='',max_length=100)
    slug = models.CharField(default='',max_length=100)

    # class Meta:
    #     ordering = 'name'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/{self.slug}/'

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(default='',max_length=100)
    description = models.TextField(default='')
    active = models.BooleanField(default=True)
    price = models.IntegerField(default=0)
    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    img = models.ImageField(null=True)
    slug = models.SlugField()
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("web:proinfo", kwargs={
            'slug':self.slug
        })

    def get_absolute_url_with_cat(self):
        return f'/{self.category.slug}/{self.slug}/'


    def get_add_to_cart_url(self):
        return reverse("web:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("web:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return int(self.quantity * self.item.price)

    # def get_amount_saved(self):
    #     return self.get_total_item_price() - self.get_total_discount_item_price()
    #
    # def get_final_price(self):
    #     if self.item.discount_price:
    #         return self.get_total_discount_item_price()
    #     return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    create = models.DateTimeField(default = timezone.now)
    ordered = models.BooleanField(default=False)
    shipinfor = models.ForeignKey(
        'ShipInfor', related_name='shipinfor', on_delete=models.SET_NULL, blank=True, null=True)
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        return total

    def __str__(self):
        return self.user.username

class ShipInfor(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'ShipInfor'

# class Customer(models.Model):
#     full_name = models.CharField(max_length=255)
#     phone = models.CharField(max_length=255)
#     address = models.CharField(max_length=255)
#     content = models.TextField(default='')
#     # order = models.ForeignKey(Order, on_delete=models.CASCADE)
#     def __str__(self):
#         return self.full_name

web/website/forms.py
from django import forms


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)

class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    name = forms.CharField(required=False)
    phone = forms.CharField(required=False)
    # shipping_zip = forms.CharField(required=False)
    #
    # billing_address = forms.CharField(required=False)
    # billing_address2 = forms.CharField(required=False)
    # billing_zip = forms.CharField(required=False)
    #
    # same_billing_address = forms.BooleanField(required=False)
    # set_default_shipping = forms.BooleanField(required=False)
    # use_default_shipping = forms.BooleanField(required=False)
    # set_default_billing = forms.BooleanField(required=False)
    # use_default_billing = forms.BooleanField(required=False)

web/product/views.py
from django.shortcuts import render

# Create your views here.

web/website/views.py
from django.shortcuts import render, render_to_response, get_object_or_404, redirect
from django.views import View
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Category,Product,Order,OrderItem, ShipInfor
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.views.generic import ListView, DetailView
from django.contrib import messages
from .forms import CheckoutForm
# Create your views here.


#
# class HomeView(ListView):
#     paginate_by = 10
#     model = Product
#     template_name = "page/products.html"

class HomeView(ListView):
    paginate_by = 10
    model = Product
    template_name = "page/products.html"
    list_cat =  Category.objects.all()

# def Category(request):
#     list_cat =  Category.objects.all()
#     return render(request,"page/products.html",{"listcat":list_cat})



# def Productcat(request, id):
#     list_cat =  Category.objects.all()
#     list_pro_cat = Product.objects.filter(category = id)
#     return render(request,"page/productcat.html",{"listcat":list_cat,"listpro":list_pro_cat})


class ProductDetailView(DetailView):
    model = Product
    template_name = "page/pro_info.html"


class CheckoutView(View):
    def get(self, *args, **kwargs):
        form = CheckoutForm()
        context = {
            'form':form
        }
        return render(self.request, "page/checkout.html",context)

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():
                shipping_address = form.cleaned_data.get("shipping_address")
                name = form.cleaned_data.get("name")
                phone = form.cleaned_data.get("phone")
                shipinfor = ShipInfor(
                    user=self.request.user,
                    address=shipping_address,
                    name=name,
                    phone=phone,
                )
                shipinfor.save()
                order.shipinfor = shipinfor
                order.save()
                return redirect('/')
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("wed:order-summary")
        messages.warning(self.request, "Thanh toán không thành công")
        return redirect('web:checkout')

class OrderSummaryView(LoginRequiredMixin,View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'page/shoppingcart.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")


@login_required
def add_to_cart(request, slug):
    item = get_object_or_404(Product, slug = slug)
    order_item, created  = OrderItem.objects.get_or_create(
        item = item,
        user = request.user,
        ordered = False
    )
    order_qs = Order.objects.filter(user = request.user, ordered = False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug = item.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item quantity was updated.")
            return redirect("web:order-summary")
        else:
            order.items.add(order_item)
            messages.info(request, "This item was added to your cart.")
            return redirect("web:order-summary")
    else:
        order = Order.objects.create(user = request.user)
        order.items.add(order_item)
        messages.info(request, "This item was added to your cart.")
        return redirect("web:order-summary")

@login_required
def remove_from_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, "This item was removed from your cart.")
            return redirect("web:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            redirect("web:proinfo",slug =slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("web:proinfo",slug =slug)

    return redirect("web:proinfo",slug =slug)

@login_required
def remove_single_item_from_cart(request, slug):
    item = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order item is in the order
        if order.items.filter(item__slug=item.slug).exists():
            order_item = OrderItem.objects.filter(
                item=item,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.items.remove(order_item)
            messages.info(request, "This item was removed from your cart.")
            return redirect("web:order-summary")
        else:
            messages.info(request, "This item was not in your cart")
            redirect("web:order-summary",slug =slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("web:proinfo",slug =slug)

    return redirect("web:proinfo",slug =slug)

# def Cat(request):
#     list_cat =  Category.objects.all()
#     # allproduct = Product.objects.all()
#     # product_cat = Product.objects.get(pk = )
#     return render(request,"/page/products.html",{"listcat":list_cat})




#   def Proinfo(request, pro_id):
#     list_cat =  Category.objects.all()
#     pro_ = Product.objects.get(pk = pro_id)
#     return render(request,"page/pro_info.html",{"listcat":list_cat,"pro":pro_})

# cart = {}
# def addcart(request):
#     if request.is_ajax():
#         id = request.POST.get('id')
#
#     pro_detail = Product.objects.get(pk = id)
#
#     if id in cart.keys():
#         item_cart = {
#             'name':pro_detail.title,
#             'price':pro_detail.price,
#             'img':str(pro_detail.img),
#             'num':int(cart[id]['num'])+1,
#         }
#     else:
#         item_cart = {
#             'name': pro_detail.title,
#             'price': pro_detail.price,
#             'img': str(pro_detail.img),
#             'num': 1,
#         }
#     order = Order
#
#     order_item = OrderItem
#     order_item.item = pro_detail.id
#     order.items = order_item
#
#     order.save()
#     order_item.save()
#
#     cart[id] = item_cart
#     request.session['cart'] = cart
#     cart_info = request.session['cart']
#     html = render_to_string('page/addcart.html',{'cart':cart_info})
#     return HttpResponse(html)
#
# def shoppingcart(request):
#     list_cat = Category.objects.all()
#     carts = request.session['cart']
#     total = 0
#     order = Order
#     for key,value in carts.items():
#         total += int(value['price'])
#
#     cf = Cus_Form
#     order.user = cf.id
#     order.save()
#     return render(request,'page/shoppingcart.html',{"listcat":list_cat,'total':total,'cf':cf})
#
# def getshoping(request):
#     if request.method == "POST":
#         cf = Cus_Form(request.POST)
#         if cf.is_valid():
#             cf.save()
#             return HttpResponse("successfull!!")
#     else:
#         return HttpResponse("not post")
#

web/website/templates/page/addcart.html
{{cart}}

web/website/templates/page/checkout.html
!DOCTYPE html>
<html lang="en">

<head>
   {% load static %}
   <meta charset="UTF-8" />
   <link rel="preconnect" href="https://fonts.googleapis.com" />
   <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet" />
   <link href="https://fonts.googleapis.com/css2?family=Ceviche+One&family=Quicksand&display=swap" rel="stylesheet" />
   <link rel="stylesheet" href="{% static 'page/css/Style.css' %} " />
   <link rel="stylesheet" href="{% static 'page/css/responsive.css' %} ">
   <link rel="stylesheet" href="{% static 'page/img/fontawesome-free-5.12.1-web/css/all.css' %}" />
   <link rel="stylesheet" href="{% static 'page/css/order.css' %} " />
<!--   <script src="./src/validator.js"></script>-->
   <title>NAK Shop</title>
</head>

<body>
   <header>
      <div class="nav">
         <ul class="nav-list">
            <li><a href="/">Trang chủ</a></li><i class="fas fa-chevron-down"></i>
            <li><a href="#">Tin Tức</a></li>
            <li><a href="#footer">Liên Hệ</a></li>
         </ul>
<!--         <div class="login-register">-->
<!--            <a href="#" class="js-login">Đăng Nhập</a>|<a href="#" class="js-register">Đăng Ký</a>-->
<!--         </div>-->
      </div>
      <div class="sub-header">
         <span class="sign">Nak shop</span>
         <i class="slogan">Mua sắm thả ga! Săn voucher cực khủng trong hôm nay!</i>
      </div>
      <div class="nav-content">
         <ul class="nav-content-list">
            {% if listcat%}
               {% for cat in listcat %}
                  <li><a href="/page/productcat/{{cat.id}}" typeproduct="{{cat.title}}">{{cat.title}}</a></li>
               {% endfor%}
            {% else %}
                <li><a href="#" typeproduct="{{cat.title}}">Empty!!</a></li>
            {% endif %}
         </ul>
         <div class="search">
            <input class="search-ip" type="text" placeholder="Bạn muốn mua gì ?" />
            <a href="#"><i class="fas fa-search"></i></a>
         </div>
         <div class="cart-icon">
            <a href="#" onclick="openModal($('.cart'))">
               Giỏ Hàng
               <i class="fas fa-shopping-cart"></i>
            </a>
         </div>
      </div>
   </header>

      <div class="content">
         <p>
            Do ảnh hưởng của dịch Covid-19, một số khu vực có thể nhận hàng chậm
            hơn dự kiến. Nak shop đang nỗ lực giao các đơn hàng trong thời gian
            sớm nhất. Cám ơn sự thông cảm của quý khách!
         </p>
         <div class="content-container">
            <div class="content-container-body">
               <h3>Thông tin giao hàng</h3>
               <form class="form-order" method="post" action="">
                  {% csrf_token %}
                     <label for="">
                        <h4>Địa chỉ giao hàng</h4>
                     </label>
                        {{form.shipping_address}}
                     <br>
                     <span class="message-error"></span>
                     <label for="">
                        <h4>Tên người nhận</h4>
                     </label>
                        {{form.name}}
                     <br>
                     <span class="message-error"></span>
                     <label for="">
                        <h4>Số điện thoại</h4>
                     </label>
                        {{form.phone}}
                     <br>
                     <span class="message-error"></span>
                  <p>(Thanh toán khi nhận hàng)</p>
                  <div class="submit"><button>ĐẶT MUA</button></div>
               </form>

            </div>
         </div>
      </div>

   <footer id="footer">
      <div class="customer-support">
         <h3>Hỗ trợ khách hàng</h3>
         <p>Hotline: 083388833</p>
         <p>(Tổng đài hỗ trợ 24/24, phí gọi 1000đ/phút)</p>
      </div>
      <div class="support">
         <h3>Hợp tác</h3>
         <p><a href="https://www.facebook.com/anhkietdepcmntrai">@NAK</a></p>
      </div>
      <div class="connect">
         <h3>Kết nối với chúng tôi</h3>
         <a href=""><i class="fab fa-facebook"></i></a>
         <a href=""><i class="far fa-envelope"></i></a>
         <a href=""><i class="fab fa-youtube-square"></i></a>
      </div>
   </footer>

   <div class="modal">
      <div class="modal-form"></div>
   </div>

   <script src="{% static 'page/src/index.js' %}"></script>
</body>

</html>

web/website/templates/page/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% load i18n %}
{% load account socialaccount %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
  <main>
    <div class="container">
      <section class="mb-4">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
          <h1>{% trans "Sign In" %}</h1>

          {% get_providers as socialaccount_providers %}

          {% if socialaccount_providers %}
          <p>{% blocktrans with site.name as site_name %}Please sign in with one
          of your existing third party accounts. Or, <a href="{{ signup_url }}">sign up</a>
          for a {{ site_name }} account and sign in below:{% endblocktrans %}</p>

          <div class="socialaccount_ballot">

            <ul class="socialaccount_providers">
              {% include "socialaccount/snippets/provider_list.html" with process="login" %}
            </ul>

            <div class="login-or">{% trans 'or' %}</div>

          </div>

          {% include "socialaccount/snippets/login_extra.html" %}

          {% else %}
          <p>{% blocktrans %}If you have not created an account yet, then please
          <a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
          {% endif %}

          <form class="login" method="POST" action="{% url 'account_login' %}">
            {% csrf_token %}
            {{ form|crispy }}
            {% if redirect_field_value %}
            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
            {% endif %}
            <a class="btn btn-default" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>
            <button class="btn btn-primary" type="submit">{% trans "Sign In" %}</button>
          </form>
          </div>
        </div>
      </section>
    </div>
  </main>

{% endblock %}


</body>
</html>

web/website/templates/page/productcat.html
{% extends 'page/index.html' %}
{% load static %}

{% block content %}

    {% for pro in listpro %}
       <li class="products">
          <a href="/page/pro_info/{{pro.id}}" index="${i}"><img src="{% static 'page/img/'%}{{pro.img}}" alt="product" /></a>
          <div class="products-content">
             <p class="price">{{ pro.price }}đ</p>
             <p class="description">{{ pro.title }}</p>
             <button class="buy js-buy" onclick="addcart({{pro.id}})">Thêm vào giỏ hàng</button>
          </div>
       </li>
    {%endfor%}

{% endblock %}

web/website/templates/page/products.html
{% extends 'page/index.html' %}
{% load static %}

{% block content %}

    {% for pro in object_list %}
       <li class="products">
          <a href="{{pro.get_absolute_url}}" index="{{pro.id}}"><img src="{% static 'page/img/'%}{{pro.img}}" alt="product" /></a>
          <div class="products-content">
             <p class="price">{{ pro.price }}đ</p>
             <p class="description">{{ pro.title }}</p>
<!--                 <button class="buy js-buy" onclick="pro.get_add_to_cart_url">Thêm vào giỏ hàng</button>-->
          </div>
       </li>
    {%endfor%}

{% endblock %}

web/website/templates/page/shoppingcart.html
!DOCTYPE html>
<html lang="en">

<head>
   {% load static %}
   <meta charset="UTF-8" />
   <link rel="preconnect" href="https://fonts.googleapis.com" />
   <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet" />
   <link href="https://fonts.googleapis.com/css2?family=Ceviche+One&family=Quicksand&display=swap" rel="stylesheet" />
   <link rel="stylesheet" href="{% static 'page/css/Style.css' %} " />
   <link rel="stylesheet" href="{% static 'page/css/responsive.css' %} ">
   <link rel="stylesheet" href="{% static 'page/img/fontawesome-free-5.12.1-web/css/all.css' %}" />
   <link rel="stylesheet" href="{% static 'page/css/order.css' %} " />
<!--   <script src="./src/validator.js"></script>-->
   <title>NAK Shop</title>
</head>

<body>
   <header>
      <div class="nav">
         <ul class="nav-list">
            <li><a href="/">Trang chủ</a></li><i class="fas fa-chevron-down"></i>
            <li><a href="#">Tin Tức</a></li>
            <li><a href="#footer">Liên Hệ</a></li>
         </ul>
<!--         <div class="login-register">-->
<!--            <a href="#" class="js-login">Đăng Nhập</a>|<a href="#" class="js-register">Đăng Ký</a>-->
<!--         </div>-->
      </div>
      <div class="sub-header">
         <span class="sign">Nak shop</span>
         <i class="slogan">Mua sắm thả ga! Săn voucher cực khủng trong hôm nay!</i>
      </div>
      <div class="nav-content">
         <ul class="nav-content-list">
            {% if listcat%}
               {% for cat in listcat %}
                  <li><a href="/page/productcat/{{cat.id}}" typeproduct="{{cat.title}}">{{cat.title}}</a></li>
               {% endfor%}
            {% else %}
                <li><a href="#" typeproduct="{{cat.title}}">Empty!!</a></li>
            {% endif %}
         </ul>
         <div class="search">
            <input class="search-ip" type="text" placeholder="Bạn muốn mua gì ?" />
            <a href="#"><i class="fas fa-search"></i></a>
         </div>
         <div class="cart-icon">
            <a href="#" onclick="openModal($('.cart'))">
               Giỏ Hàng
               <i class="fas fa-shopping-cart"></i>
            </a>
         </div>
      </div>
   </header>

      <div class="content">
         <p>
            Do ảnh hưởng của dịch Covid-19, một số khu vực có thể nhận hàng chậm
            hơn dự kiến. Nak shop đang nỗ lực giao các đơn hàng trong thời gian
            sớm nhất. Cám ơn sự thông cảm của quý khách!
         </p>
         <div class="content-container">
            <div class="content-container-header">
               <h3>Đơn hàng</h3>
               <ul>
                  {% for order_item in object.items.all %}
                     <li>
                        <div class="info">
                           <img src="{% static 'page/img/' %}{{order_item.item.img}}" alt="img" />
                           <p>{{order_item.item.title}}</p>
                        </div>
                        <div class="quantity">

                           <p>số lượng :<a href="{% url 'web:add-to-cart' order_item.item.slug %}">+</a> {{order_item.quantity}} <a href="{% url 'web:remove-single-item-from-cart' order_item.item.slug%} ">-</a></p>

                        </div>
                        <p class="total-price-product">Thành tiền:{{order_item.get_total_item_price}}đ </p>
                        <a id="dlt" href="{% url 'web:remove-from-cart' order_item.item.slug %}">Xóa khỏi giỏ hàng</a>
                     </li>
                  {% endfor %}

               </ul>
               <br />
               <h4 class="total-price">Tổng tiền:{{object.get_total}}đ</h4>
            </div>
            <div class="content-container-body">
                  <div class="submit"><button><a href="{% url 'web:checkout' %}" >ĐẶT MUA</button></a></div>
            </div>
         </div>
      </div>

   <footer id="footer">
      <div class="customer-support">
         <h3>Hỗ trợ khách hàng</h3>
         <p>Hotline: 083388833</p>
         <p>(Tổng đài hỗ trợ 24/24, phí gọi 1000đ/phút)</p>
      </div>
      <div class="support">
         <h3>Hợp tác</h3>
         <p><a href="https://www.facebook.com/anhkietdepcmntrai">@NAK</a></p>
      </div>
      <div class="connect">
         <h3>Kết nối với chúng tôi</h3>
         <a href=""><i class="fab fa-facebook"></i></a>
         <a href=""><i class="far fa-envelope"></i></a>
         <a href=""><i class="fab fa-youtube-square"></i></a>
      </div>
   </footer>

   <div class="modal">
      <div class="modal-form"></div>
   </div>

   <script src="{% static 'page/src/index.js' %}"></script>
</body>

</html>